SudokuSolverCore/Models/ErrorViewModel.cs
using System;

namespace SudokuSolverCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SudokuSolverCore/ViewModels/SudokuWithListItemsViewModel.cs
using Shared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SudokuSolverCore.ViewModels
{
    public class SudokuWithListItemsViewModel
    {
        public SudokuModel Model { get; set; }
        public IEnumerable<string> DropDownOptions { get; set; }
    }
}

SudokuSolverCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SudokuSolverCore.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SudokuSolverCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SudokuSolverCore/Controllers/SudokuController.cs
using Logic.Algorithms;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SudokuSolverCore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SudokuSolverCore.Controllers
{
    [AllowAnonymous]
    public class SudokuController : Controller
    {
        public readonly Repositories.MockingRepository.IMockingRepo _repo = Repositories.MockingRepository.MockingRepo.GetMockingRepo();
        public IActionResult Sudoku()
        {
            var board =_repo.GetSudoku(1);
            Shared.StaticResources.StaticValues.CurrentSudokuTemplate = board;
            SudokuWithListItemsViewModel SudokuVM = new SudokuWithListItemsViewModel() { Model = board };
            return View(SudokuVM);
        }
        [Route("/Sudoku/Sudoku/{id}")]
        public IActionResult Sudoku(int id)
        {
            if (id < 5)
            {
                var board = _repo.GetSudoku(id);
                SudokuWithListItemsViewModel SudokuVM = new SudokuWithListItemsViewModel() { Model = board };
                return View(SudokuVM);
            }
            else
            {
                var board = SudokuMainSolver.SolveSudoku(id, Shared.StaticResources.StaticValues.CurrentSudokuTemplate);
                SudokuWithListItemsViewModel SudokuVM = new SudokuWithListItemsViewModel() { Model = board };
                return View(SudokuVM);
            }
        }
    }
}

SudokuSolverCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SudokuSolverCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SudokuSolverCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SudokuSolverCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SudokuSolverCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SudokuSolverCore/Views/Sudoku/Sudoku.cshtml
@model SudokuSolverCore.ViewModels.SudokuWithListItemsViewModel

<style>
    .buttonContainer {
        display: flex;
    }

    td {
        border-right: solid 1px #808080;
        border-left: solid 1px #808080;
    }
    /* Dropdown Button */
    .dropbtn {
        background-color: #3498DB;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        cursor: pointer;
    }

        /* Dropdown button on hover & focus */
        .dropbtn:hover, .dropbtn:focus {
            background-color: #2980B9;
        }

    /* The container <div> - needed to position the dropdown content */
    .dropdown {
        position: relative;
        display: inline-block;
    }

    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        /* Links inside the dropdown */
        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            /* Change color of dropdown links on hover */
            .dropdown-content a:hover {
                background-color: #ddd
            }

    /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
    .show {
        display: block;
    }

    table tr:nth-of-type(3n) {
        border-bottom: 3px solid #808080;
    }

    table tr > td:nth-of-type(3n) {
        border-right: 3px solid #808080;
       
    }

    td {
        height: 50px;
        width: 50px;
        text-align: center;
    }
</style>
<div class="gameContainer">
    <div class="sudokuSidebar">
        <div class="clearfix"></div>
        <div class="buttonContainer">
            <div class="dropdown">
                <button onclick="myFunction()" class="dropbtn">Choose start template</button>
                <div id="myDropdown" class="dropdown-content">
                    <a asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="1">Logical template</a>
                    <a asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="2">Guessing template</a>
                    <a asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="3">Empty template</a>
                    <a asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="4">Hardest in the world template</a>

                </div>
            </div>
            <form method="post">
                <div class="buttonContainer">

                    @*<button class="btn btn-info m-2" type="button" value="Solve Logical" onclick="location.href='@Url.Action("SudokuSolvedLogical", "Sudoku")'">Solve Logical</button>*@
                    <button asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="5" class="btn btn-info m-2">Solve trough logical method</button>
                    <div class="clearfix"></div>
                    <button asp-controller="Sudoku" asp-action="Sudoku" asp-route-id="6" class="btn btn-info m-2">Solve trough guessing method</button>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
    </div>
    <div class="sudokuMainContainer" id="board">
        <table class="table table-dark rounded border m-2">
            @for (int i = 0; i < 9; i++)
            {
<tr class="sudokuRow">
    @for (int j = 0; j < 9; j++)
    {
<td>
    @Model.Model.Sudoku[i][j].value
</td>}
</tr>            }
        </table>
        <p></p>
    </div>
</div>
<script>
    /* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown menu if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>